Algoritmo "CadastroDeAluno"
// Data atual  : 02/09/2026
Var
// Declaração das variáveis com seus respectivos tipos
   nome, sexo : caractere
   idade : inteiro
   altura, peso : real
Inicio
// Entrada de dados
   escreva("Digite o seu nome: ")
   leia(nome)

   escreva("Digite a sua idade: ")
   leia(idade)

   escreva("Digite a sua altura (ex: 1.75): ")
   leia(altura)

   escreva("Digite o seu peso em kg (ex: 70.5): ")
   leia(peso)

   escreva("Digite o seu sexo (F para Feminino / M para Masculino): ")
   leia(sexo)

   // Saída de dados (Mostrando o que foi digitado)
   escreval("-----------------------------")
   escreval("      DADOS CADASTRADOS      ")
   escreval("-----------------------------")
   escreval("Nome: ", nome)
   escreval("Idade: ", idade, " anos")
   escreval("Altura: ", altura, " metros")
   escreval("Peso: ", peso, " Kg")
   escreval("Sexo: ", sexo)
   escreval("-----------------------------")

Fimalgoritmo



